project:
  type: website

website:
  title: "Tajurba"
  navbar:
    background: primary
    search: true
    left:
      - text: "Journal"
        file: journal/index.qmd
      - text: "Read"
        file: read/index.qmd
      - text: "Listen"
        file: listen/index.qmd
      - text: "Think"
        file: think/index.qmd
      - text: "Code"
        file: code/index.qmd

  sidebar:
    - title: "Journal"
      style: "docked"
      search: true
      background: light
      contents: 
        - journal/index.qmd
        - auto: journal/*
#
    - title: "Read"
      contents:
        - read/index.qmd
        - auto: read/*
#
    - title: "Listen"
      contents: 
        - listen/index.qmd
        - section: "Group Meetings"
          contents:
          - auto: listen/group-meetings/*
#
    - title: "Think"
      contents:
        - think/index.qmd
        - auto: think/*

    - title: "Code"
      contents:
        - code/index.qmd
        - auto: code/*

  page-navigation: true
  repo-url: https://github.com/banskt/nygc-notes
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
