---
title: 2023, May
---

## 2023-04-16

  - Clean notebook files, set up workflow for publishing NPD notebooks.
  - Read more about conventional PCA and weighted PCA.

## 2023-04-15

  - Implement [Delchambre's weighted PCA](https://doi.org/10.1093/mnras/stu2219).
  - I observed hidden structures for the summary statistics in conventional PCA,
  but I did not observe structures in weighted PCA. Why?

## 2023-04-12

  - Implement preprocessing of $\beta$ and SE matrix in Python. Required for playing with PCA
  and understanding the structure of the data.

## 2023-04-11

  - Meeting with David. We discussed data cleaning and its effect on weighted PCA. See Slack for details.
  - Probgen reading club, [presented by Scott Adamson](../listen/journal-club/2023-05-11-coop-book-chapter-8.qmd). 
  Chapter 8 from Population Genetics book by Graham Coop.

## 2023-04-10

  - Knowles Lab Meeting, [presented by Brielin Brown](../listen/group-meeting/2023-05-10-brielin-brown.qmd).
  - Meeting with Matthew on GradVI manuscript. Reformat introduction.

## 2023-04-09

  - GradVI manuscript - reorganize methods and introduction.

## 2023-04-08

  - NPD Summary Statistics. Look at weighted PCA after data cleaning.
  It appears that there is not much distinguishable from the principal components.

## 2023-04-05

  - Last date for NYGC onboarding. Finish courses and benefits election.
  - Set up Macbook Pro for work.

## 2023-04-04

  - Make changes and create pull request on DSC for supporting `collections.abc` and rpy2 v3.5.11.
  - Numerical experiments for dense linear regression for correlated variables.
  - Plot results (ELBO, RMSE, runtime) for dense linear regression for correlated variables.
  - Run more replicates for the above simulation.
  - [Seminar by Julia Domingo](../listen/seminar/2023-05-04-julia-domingo.qmd)

## 2023-04-03

  - GradVI plots without colors in scatterplot.
  - GradVI runtime-per-iteration plot with $\log_{10}$ scale.
  - Meeting with Matthew. 

## 2023-04-02

  - Run genlasso with large $n$ for one simulation at the NYGC cluster.
  - Onboarding - Health insurance.
  - Genlasso running into out-of-memory error.
  - Make changes in GradVI to run without creating the $\mathbb{H}$ matrix.

## 2023-04-01

  - The GradVI trendfiltering runtime experiments have failed. 
  Troubleshoot: 40G memory is not enough for the jobs. 
  I removed jobs with $n = (10^5, 10^6)$ and submitted new jobs with 100G 
  of memory in interactive node. 
  The idea is to run the large jobs separately for GradVI.
  - Simulate first order trend filtering data with less memory.
  - How to run GradVI without generating $\mathbf{H}$ matrix?
  I derived equations for obtaining $d_j$ without generating the $\mathbf{H}$ matrix
  and made the required changes in the GradVI software to run without generating
  the matrix. This introduced a bug which prevents running trend filtering for higher orders.
