---
title: 2023, April
---

## 2023-04-26

  - Group meeting, [presentation by Scott Adamson](../listen/group-meeting/2023-04-26-scott-adamson.qmd)
  - Setup Python workbench for NYGC cluster. [See workflow](../code/2023-04-25-cluster-setup.qmd)

## 2023-04-25

  - GradVI. Scatterplot comparing number of iterations, total runtime and ELBO between 
  (a) GradVI compound and CAVI, and (b) GradVI direct and CAVI) for strongly correlated ($r^2 = 0.99$) covariates
  in case of multiple linear regression. Create new DSC simulation to calculate runtime
  of trendfiltering in higher dimension.
  - Meeting with Matthew. Discuss Stochastic Gradient Descent (SGD) and natural gradients. 
  Discuss list of things to be done before the manuscript can be reviewed by Matthew.

## 2023-04-24

  - Fix RStudio server.
  - Submit jobs for trend filtering (RCC at UChicago).

## 2023-04-21

  - Meeting with Ekene and Gilead. They are working on improving SparsePro 
  using gradient descent optimization for estimating the coefficients $w$ for functional annotations.
  - NPD. Fix errors in extraction of summary statistics of selected variants from PGC. 
  Clean the R code for reading all the data. 
  - RStudio server is not showing plots

## 2023-04-20

  - Journal Club. Anjali discussed the article, 
  "Adjusting for common variant polygenic scores improves yield in rare variant association analyses",
  Jurgens et al, *Nature Genetics* **55**, 544–548 (2023). 
  [Link](https://doi.org/10.1038/s41588-023-01342-w).
  Using 65 traits from the UK Biobank data,
  the authors showed that including PGS as a fixed-effect covariate in linear mixed model analysis
  (using GENESIS) improved the yield and discovery power for rare variant association signal.
  The authors constructed PGS for each trait based on two different methods: (1) lead-SNP,
  and (2) [PRS-CS](https://doi.org/10.1038/s41467-019-09718-5), which applies a Bayesian regression framework to identify posterior variant effect sizes 
  based on a continuous shrinkage prior, which is directly learnt from the data
  - NPD. Tidy the selection of variants from GTEx and PGC summary statistics, 
  extract the summary statistics of selected variants from PGC, OpenGWAS and GTEx.

## 2023-04-19

  - Group meeting, [presentation by Tatsuhiko Naito](../listen/group-meeting/2023-04-19-tatsuhiko-naito.qmd)
  - ADSP meeting. Anjali discussed the p-value distributions from FST.
  - Setup RStudio at NYGC cluster.
  - NPD. David shared the [pilot project for NPD](https://github.com/daklab/npd_sumstats).
  I looked at the data cleaning of the summary statistics.
  - Setup the NPD website.

## 2023-04-18

  - GradVI. Discuss figure with Peter.
  - Setup cluster access at NYGC.

## 2023-04-17
  
  - GradVI. Simulation complete for linear regression with correlated variables, $r^2 = 0.99$. 
  Run `dscquery` for collecting results. Compare niter between GradVI (compound) and GradVI (direct) and mr.ash.
  Share figure on slack.
  - General Safety and Compliance Orientation

## 2023-04-14

  - [Raj/Knowles joint group meeting](../listen/group-meeting/2023-04-14-adsp-group-meeting.qmd) at ISMMS.
  - Kick-off meeting with Niamh.

## 2023-04-13

  - Setup navigation in Quarto journal.
  - Probgen Reading Club, [presentation by Sei Chang](../listen/journal-club/2023-04-13-coop-book-chapter-6.qmd)
  - GradVI. Create new notebook for linear regression with correlated variables, 
  find examples where GradVI converge faster than CAVI, set up DSC simulation pipeline for those examples,
  submit DSC job on interactive node at RCC, check jobs are running properly (no error in data generation, lasso initialization).


## 2023-04-12

This is the beginning of my NYGC journal, on my third day here.

  - Attend general group meeting, [presentation by Anjali](../listen/group-meeting/2023-04-12-adas-group-meeting.qmd).
  - Attend ADSP group meeting.
  - Setup Quarto journal.
  - Work on GradVI manuscript.
