---
title: 2023-07-05
---

# Isoform-specific functions of RNA binding proteins

## Presentation by Megan Schertzer

Alternative splicing regulates ~95% of multi-exon genes.
It is regulated by (1) *cis*-acting pre-messenger RNA sequences,
and (2) *trans*-acting RNA-binding proteins.

**Project 1.**
Pooled RNA-IP approach to investigate variant effects on RBP binding and splicing.

*Project 2.*
Isoform-specific functions using Cas13 knockdown and cDNA overexpression.

AS changes protein output to define cell-type or condition specific functions.
Potential effects:

  - Protein localization
  - Nucleic acid binding
  - Co-factor binding

(RBPs show isoforms themselves.)

**RBFOX2**\
well-established splicing factor with complex isoform structure.
Alternative start sites, and 2 alternative junctions.

### Cas13 RNA knockdown

Design sgRNA for junction level, knockdown and measure qPCR.
High throughput, versatile (can target exons, alternative starts/ends and alternative 5'/3' sites),
targets endogeneous transcripts, doesn't change underlying DNA locus.
Disadvantages: some isoforms do not have fully unique seq for gRNA targeting,
limited to studying isoforms expressed in cell type,
feedback loop (?).

### cDNA overexpression

- Can express any isoform of interest
- Can express isoforms at similar levels
- cleaner experiments using FLAG tag to isolate isoforms
- Disadvantage: not scalable.
- Can help to study protein localization, RNA binding

How to summarize potential functional differences of RBP isoforms
and prioritize isoforms for follow-up studies?

How to scale up the cDNA overexpression system?
